[build]
  command = "npm install && npm run build"
  publish = "build"
  [build.caching]
    enabled = true
    paths = ["node_modules/.cache", "public/build"]

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"